name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}

    - name: update ruby
      run: | 
            brew install rbenv
            rbenv install "$(< .ruby-version)"
            rbenv global "$(< .ruby-version)"
            echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
            export RBENV_ROOT=$BREW_ROOT/rbenv/
            source ~/.bash_profile
            gem install bundler:1.17.2
            bundle install
            echo ::set-env name=GEM_HOME::$(gem environment gemdir)
