name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}

    - name: update ruby
      run: | 
            brew install rbenv
            rbenv install "$(< .ruby-version)"
            echo "hoge1"
            rbenv global "$(< .ruby-version)"
            echo "hoge2"
            ruby -v
            echo 'export PATH="~/.rbenv/shims:/usr/local/bin:$PATH"' \>\> ~/.bash\_profile
            echo "hoge3"
            echo 'eval "$(rbenv init -)"' \>\> ~/.bash\_profile
            echo "hoge4"
            source ~/.bash\_profile
            echo "hoge5"
            ruby -v
            echo "hoge6"
            gem install bundler:1.17.2
            echo "hoge8"
            bundle install
            echo ::set-env name=GEM_HOME::$(gem environment gemdir)
